Algoritmo "Concatenação"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Associar mensagem + variavel
// Autor(a)    : Obaminha
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Good Afternoon Short Arms")
Escreval("Digite um valor :")
Leia(numero1)
Escreval("O valor digitado é : ",numero1)


Fimalgoritmo