Algoritmo "ExemploLacodeRepeticaoPara"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Jailson
// Data atual  : 30/09/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 10 ate 1 passo -1 faca
      Escreval(contadora)
   fimpara

Fimalgoritmo