Algoritmo "Exibir Mensagem"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Exibir uma mensagem na tela do computador
// Autor(a)    : Obaminha
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Jailson")
Escreva("Camisa 10")

Fimalgoritmo