Algoritmo "Exibir valor de uma variável"
// Disciplina  :[Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Exibir o valor de uma variável
// Autor(a)    : Obaminha
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis

numero1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número :")
Leia(numero1)
Escreval(numero1)

Fimalgoritmo